{
 "title": "Unifi LTE Modem",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values(unifi_lte_info, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (name, model, lte_signal, name, lte_networkoperator, lte_radio_mode, lte_ip, lte_cell_id, lte_imei, lte_iccid, lte_pdptype, lte_pdptype, lte_band) (unifi_lte_info{name=\"$name\"})"
    }
   ]
  },
  {
   "title": "Signal",
   "type": "timeseries",
   "description": "rssi: Received signal strength indication\n\nRSRQ: reference signals received quality\n\nRSRP: reference signals received quality",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "unifi_lte_rssi{name=\"$name\"}",
     "legendFormat": "rssi ({{name}})"
    },
    {
     "expr": "unifi_lte_rsrp{name=\"$name\"}",
     "legendFormat": "rsrp ({{name}})"
    },
    {
     "expr": "unifi_lte_rsrq{name=\"$name\"}",
     "legendFormat": "rsrq ({{name}})"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(unifi_total_tx_bytes{name=\"$name\"}[$__interval])",
     "legendFormat": "Bytes Transmited ({{name}})"
    },
    {
     "expr": "-rate(unifi_total_rx_bytes{name=\"$name\"}[$__interval])",
     "legendFormat": "Bytes Received ({{name}})"
    }
   ]
  },
  {
   "title": "Send/Receive Channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "unifi_lte_tx_chan{name=\"$name\"}",
     "legendFormat": "{{name}} (Send Channel)"
    },
    {
     "expr": "unifi_lte_rx_chan{name=\"$name\"}",
     "legendFormat": "{{name}} (Receive Channel)"
    }
   ]
  }
 ]
}